## write a function that will pickle the clean_dataframe and cycle_list data once processed from exported xls files
  
I know that pickle is not ideal but it will allow me to save the pandas dataframe and easily open it again when I want to plot.

In [9]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import pickle

import dataprep

In [10]:
clean_dataframe, cycle_list = dataprep.plotprep('example_data.xls', 2)

Rest step removed
Reverse Mode: First cycle contains only initial discharge
36 complete cycles after intial discharge
Final cycle only contains charge data


In [11]:
# now save this data into a pickle file with a function
def pickle_store(clean_dataframe, cycle_list, filename):
    """
    docstring
    """
    pickle_data = [clean_dataframe, cycle_list]
    pickle.dump(pickle_data, open('example_pickle.pickle', 'wb'))
    print('cycling data stored to {}'.format(filename))

In [12]:
pickle_store(clean_dataframe, cycle_list, 'example_pickle.pickle')

cycling data stored to example_pickle.pickle


In [20]:
# now a simple function for unpacking that pickle data as needed for plotting functions
# I will need to update plotting functions in the future to only take a single variable instead
# of the two that they now take `clean_dataframe` and `cycle_list`

def pickle_load(filename):
    """
    docstring
    """
    clean_dataframe, cycle_list = pickle.load(open(filename, 'rb'))
    return clean_dataframe, cycle_list

In [21]:
clean_dataframe, cycle_list = pickle_load('example_pickle.pickle')

In [22]:
clean_dataframe

index    test_time step_time voltage current capacity scapacity  \
3            1     00:00:00  00:00:00   2.346       0        0         0   
4            2     00:10:00  00:10:00  2.3449       0        0         0   
5            3     00:20:00  00:20:00  2.3449       0        0         0   
6            4     00:30:00  00:30:00  2.3441       0        0         0   
7            5     00:40:00  00:40:00  2.3445       0        0         0   
8            6     00:50:00  00:50:00  2.3441       0        0         0   
9            7     01:00:00  01:00:00  2.3445       0        0         0   
10           8     01:10:00  01:10:00  2.3445       0        0         0   
11           9     01:20:00  01:20:00  2.3434       0        0         0   
12          10     01:30:00  01:30:00  2.3434       0        0         0   
13          11     01:40:00  01:40:00  2.3438       0        0         0   
14          12     01:50:00  01:50:00  2.3434       0        0         0   
15          13     02:00:00  02:00:00   2.343       0        0         0   
16          14     02:10:00  02:10:00  2.3445       0        0         0   
17          15     02:20:00  02:20:00  2.3434       0        0         0   
18          16     02:30:00  02:30:00  2.3434       0        0         0   
19          17     02:40:00  02:40:00  2.3434       0        0         0   
20          18     02:50:00  02:50:00  2.3438       0        0         0   
21          19     03:00:00  03:00:00   2.343       0        0         0   
22          20     03:10:00  03:10:00  2.3441       0        0         0   
23          21     03:20:00  03:20:00  2.3438       0        0         0   
24          22     03:30:00  03:30:00  2.3426       0        0         0   
25          23     03:40:00  03:40:00   2.343       0        0         0   
26          24     03:50:00  03:50:00  2.3426       0        0         0   
27          25     04:00:00  04:00:00  2.3426       0        0         0   
28          26     04:10:00  04:10:00  2.3426       0        0         0   
29          27     04:20:00  04:20:00  2.3438       0        0         0   
30          28     04:30:00  04:30:00   2.343       0        0         0   
31          29     04:40:00  04:40:00   2.343       0        0         0   
32          30     04:50:00  04:50:00  2.3434       0        0         0   
...        ...          ...       ...     ...     ...      ...       ...   
130541  130317  15-06:33:37  04:49:18  2.6443   0.293    1.408     806.2   
130542  130318  15-06:33:47  04:49:28  2.6551   0.292    1.409     806.7   
130543  130319  15-06:33:57  04:49:38  2.6678   0.292     1.41     807.1   
130544  130320  15-06:34:07  04:49:48  2.6778   0.292    1.411     807.6   
130545  130321  15-06:34:17  04:49:58  2.6905   0.293    1.412     808.1   
130546  130322  15-06:34:27  04:50:08  2.7039   0.292    1.413     808.5   
130547  130323  15-06:34:37  04:50:18  2.7128   0.293    1.413       809   
130548  130324  15-06:34:47  04:50:28  2.7251   0.293    1.414     809.5   
130549  130325  15-06:34:57  04:50:38  2.7329   0.292    1.415     809.9   
130550  130326  15-06:35:07  04:50:48  2.7429   0.292    1.416     810.4   
130551  130327  15-06:35:17  04:50:58  2.7567   0.293    1.417     810.9   
130552  130328  15-06:35:27  04:51:08  2.7679   0.292    1.417     811.3   
130553  130329  15-06:35:37  04:51:18  2.7794   0.292    1.418     811.8   
130554  130330  15-06:35:47  04:51:28  2.7932   0.292    1.419     812.2   
130555  130331  15-06:35:57  04:51:38  2.8028   0.292     1.42     812.7   
130556  130332  15-06:36:07  04:51:48   2.817   0.292    1.421     813.2   
130557  130333  15-06:36:17  04:51:58  2.8289   0.293    1.421     813.6   
130558  130334  15-06:36:27  04:52:08  2.8404   0.292    1.422     814.1   
130559  130335  15-06:36:37  04:52:18   2.856   0.292    1.423     814.6   
130560  130336  15-06:36:47  04:52:28   2.865   0.292    1.424       815   
130561  130337  15-06:36:57  04:52:38  2.8798   0.292    

In [23]:
cycle_list

[[array([  43,   44,   45, ..., 4494, 4495, 4496])],
 [array([4500, 4501, 4502, ..., 9004, 9005, 9006]),
  array([ 9010,  9011,  9012, ..., 13138, 13139, 13140])],
 [array([13144, 13145, 13146, ..., 15136, 15137, 15138]),
  array([15142, 15143, 15144, ..., 16999, 17000, 17001])],
 [array([17005, 17006, 17007, ..., 18859, 18860, 18861]),
  array([18865, 18866, 18867, ..., 20672, 20673, 20674])],
 [array([20678, 20679, 20680, ..., 22490, 22491, 22492]),
  array([22496, 22497, 22498, ..., 24264, 24265, 24266])],
 [array([24270, 24271, 24272, ..., 26049, 26050, 26051]),
  array([26055, 26056, 26057, ..., 27784, 27785, 27786])],
 [array([27790, 27791, 27792, ..., 29537, 29538, 29539]),
  array([29543, 29544, 29545, ..., 31248, 31249, 31250])],
 [array([31254, 31255, 31256, ..., 32982, 32983, 32984]),
  array([32988, 32989, 32990, ..., 34665, 34666, 34667])],
 [array([34671, 34672, 34673, ..., 36378, 36379, 36380]),
  array([36384, 36385, 36386, ..., 38039, 38040, 38041])],
 [array([38045, 3